import React, { useEffect, useState } from 'react';
import { Sparkles, Check, AlertCircle, Loader2 } from 'lucide-react';
import { Modal } from '../ui/Modal';
import { createProject, listPresets, synthesizeClaudeMD } from '../../api/projects';
import { getRepo } from '../../api/git';
import type { Project, ProjectPreset, ProjectRepo, ProjectSkillLevel } from '../../api/types';
import './Projects.css';

// Accepts "https://github.com/owner/repo[/...]" or bare "owner/repo".
// Returns null if the input doesn't look like either.
function parseGithubInput(s: string): { owner: string; repo: string } | null {
  const trimmed = s.trim();
  if (!trimmed) return null;
  const url = trimmed.match(/^https?:\/\/github\.com\/([A-Za-z0-9._-]+)\/([A-Za-z0-9._-]+)(?:[/?#].*)?$/i);
  if (url) return { owner: url[1], repo: url[2].replace(/\.git$/i, '') };
  const slash = trimmed.match(/^([A-Za-z0-9._-]+)\/([A-Za-z0-9._-]+)$/);
  if (slash) return { owner: slash[1], repo: slash[2].replace(/\.git$/i, '') };
  return null;
}

interface Props {
  isOpen: boolean;
  serverId: string;
  onClose: () => void;
  onCreated: (p: Project) => void;
}

const SKILL_LEVELS: { value: ProjectSkillLevel; label: string }[] = [
  { value: 'beginner', label: 'Beginner — explain things, ask before destructive ops' },
  { value: 'intermediate', label: 'Intermediate — comfortable with most tools' },
  { value: 'expert', label: 'Expert — terse, assume context' },
  { value: 'auto', label: 'Auto — let Claude decide' },
  { value: 'custom', label: 'Custom — I will write my own preamble' },
];

// A2.0 wizard: skill slider + freeform → synthesize via the configured
// provider (Ollama in V1) → review/edit → create. Falls back to manual
// CLAUDE.md textarea if synthesis fails (503 from disabled service or
// network blip) so the wizard isn't blocked on the LLM.
export const CreateProjectWizard: React.FC<Props> = ({ isOpen, serverId, onClose, onCreated }) => {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [skillLevel, setSkillLevel] = useState<ProjectSkillLevel>('auto');
  const [presetSlug, setPresetSlug] = useState('');
  const [freeform, setFreeform] = useState('');
  const [claudeMd, setClaudeMd] = useState('');
  const [repoInput, setRepoInput] = useState('');
  const [repoStatus, setRepoStatus] = useState<'idle' | 'checking' | 'ok' | 'invalid' | 'notfound'>('idle');
  const [verifiedRepo, setVerifiedRepo] = useState<ProjectRepo | null>(null);
  const [presets, setPresets] = useState<ProjectPreset[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [synthesizing, setSynthesizing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [synthInfo, setSynthInfo] = useState<string | null>(null);

  useEffect(() => {
    if (!isOpen) return;
    listPresets().then(setPresets).catch((e) => {
      console.error('failed to load presets', e);
    });
  }, [isOpen]);

  // Reset on open
  useEffect(() => {
    if (isOpen) {
      setName('');
      setDescription('');
      setSkillLevel('auto');
      setPresetSlug('');
      setFreeform('');
      setClaudeMd('');
      setRepoInput('');
      setRepoStatus('idle');
      setVerifiedRepo(null);
      setError(null);
      setSynthInfo(null);
    }
  }, [isOpen]);

  // Validate the repo input against GitHub. Debounced so we don't fire on
  // every keystroke; runs after the user pauses for 500ms.
  useEffect(() => {
    if (!repoInput.trim()) {
      setRepoStatus('idle');
      setVerifiedRepo(null);
      return;
    }
    const parsed = parseGithubInput(repoInput);
    if (!parsed) {
      setRepoStatus('invalid');
      setVerifiedRepo(null);
      return;
    }
    setRepoStatus('checking');
    const handle = setTimeout(async () => {
      try {
        await getRepo('github', parsed.owner, parsed.repo);
        setRepoStatus('ok');
        setVerifiedRepo({ provider: 'github', owner: parsed.owner, repo: parsed.repo });
      } catch {
        setRepoStatus('notfound');
        setVerifiedRepo(null);
      }
    }, 500);
    return () => clearTimeout(handle);
  }, [repoInput]);

  const synthesize = async () => {
    if (!name.trim()) {
      setError('Name is required before synthesizing.');
      return;
    }
    setSynthesizing(true);
    setError(null);
    setSynthInfo(null);
    try {
      const res = await synthesizeClaudeMD({
        server_id: serverId,
        preset_slug: presetSlug || undefined,
        name: name.trim(),
        description: description.trim(),
        skill_level: skillLevel,
        freeform: freeform.trim(),
      });
      setClaudeMd(res.claude_md);
      setSynthInfo(`Generated by ${res.provider}. Edit below before creating.`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Synthesis failed.';
      // 503 → tell the user they can still proceed manually.
      if (/unavailable|503/i.test(msg)) {
        setError('Synthesis is offline right now. You can write the CLAUDE.md manually below.');
      } else {
        setError(msg);
      }
    } finally {
      setSynthesizing(false);
    }
  };

  const submit = async () => {
    if (!name.trim()) {
      setError('Name is required.');
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      const project = await createProject({
        server_id: serverId,
        name: name.trim(),
        description: description.trim(),
        skill_level: skillLevel,
        preset_slug: presetSlug || undefined,
        claude_md: claudeMd,
        repos: verifiedRepo ? [verifiedRepo] : undefined,
      });
      onCreated(project);
      onClose();
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Failed to create project.';
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Create project">
      <div className="wizard-form">
        {error && <div className="wizard-error">{error}</div>}

        <label>
          Name
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            maxLength={80}
            placeholder="My new project"
            autoFocus
          />
        </label>

        <label>
          Description (optional)
          <input
            type="text"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="One-line summary"
          />
        </label>

        <label>
          GitHub repository (optional)
          <input
            type="text"
            value={repoInput}
            onChange={(e) => setRepoInput(e.target.value)}
            placeholder="https://github.com/owner/repo  or  owner/repo"
          />
          {repoStatus === 'checking' && (
            <span className="wizard-repo-status"><Loader2 size={12} className="spin" /> Checking…</span>
          )}
          {repoStatus === 'ok' && verifiedRepo && (
            <span className="wizard-repo-status ok"><Check size={12} /> {verifiedRepo.owner}/{verifiedRepo.repo} verified</span>
          )}
          {repoStatus === 'invalid' && (
            <span className="wizard-repo-status"><AlertCircle size={12} /> Doesn't look like a GitHub URL or owner/repo.</span>
          )}
          {repoStatus === 'notfound' && (
            <span className="wizard-repo-status"><AlertCircle size={12} /> Repo not found or not accessible.</span>
          )}
        </label>

        <label>
          Preset (optional)
          <select value={presetSlug} onChange={(e) => setPresetSlug(e.target.value)}>
            <option value="">No preset</option>
            {presets.map((p) => (
              <option key={p.slug} value={p.slug}>{p.name}</option>
            ))}
          </select>
        </label>

        <label>
          Skill level
          <select value={skillLevel} onChange={(e) => setSkillLevel(e.target.value as ProjectSkillLevel)}>
            {SKILL_LEVELS.map((s) => (
              <option key={s.value} value={s.value}>{s.label}</option>
            ))}
          </select>
        </label>

        <label>
          Describe what you want to build
          <textarea
            value={freeform}
            onChange={(e) => setFreeform(e.target.value)}
            placeholder={'A short paragraph or two: what is this project, who is it for, what does success look like? The more specific, the better the synthesized CLAUDE.md.'}
            style={{ minHeight: 110 }}
          />
        </label>

        <button
          type="button"
          className="projects-create-btn"
          onClick={synthesize}
          disabled={synthesizing || submitting || !name.trim()}
          style={{ alignSelf: 'flex-start' }}
        >
          <Sparkles size={14} />
          {synthesizing ? 'Synthesizing…' : claudeMd ? 'Re-synthesize' : 'Synthesize CLAUDE.md'}
        </button>

        {synthInfo && <div style={{ fontSize: 12, color: 'var(--parley-text-muted, #b9bbbe)' }}>{synthInfo}</div>}

        <label>
          CLAUDE.md (review and edit before creating)
          <textarea
            value={claudeMd}
            onChange={(e) => setClaudeMd(e.target.value)}
            placeholder={'# Project notes\n\nClick Synthesize above, or write this manually.'}
            style={{ minHeight: 220 }}
          />
        </label>

        <div className="wizard-actions">
          <button className="secondary" onClick={onClose} disabled={submitting || synthesizing}>Cancel</button>
          <button className="primary" onClick={submit} disabled={submitting || synthesizing || !name.trim()}>
            {submitting ? 'Creating…' : 'Create project'}
          </button>
        </div>
      </div>
    </Modal>
  );
};
