import React, { useEffect, useState } from 'react';
import { Sparkles } from 'lucide-react';
import { Modal } from '../ui/Modal';
import { createProject, listPresets, synthesizeClaudeMD } from '../../api/projects';
import type { Project, ProjectPreset, ProjectSkillLevel } from '../../api/types';
import './Projects.css';

interface Props {
  isOpen: boolean;
  serverId: string;
  onClose: () => void;
  onCreated: (p: Project) => void;
}

const SKILL_LEVELS: { value: ProjectSkillLevel; label: string }[] = [
  { value: 'beginner', label: 'Beginner — explain things, ask before destructive ops' },
  { value: 'intermediate', label: 'Intermediate — comfortable with most tools' },
  { value: 'expert', label: 'Expert — terse, assume context' },
  { value: 'auto', label: 'Auto — let Claude decide' },
  { value: 'custom', label: 'Custom — I will write my own preamble' },
];

// A2.0 wizard: skill slider + freeform → synthesize via the configured
// provider (Ollama in V1) → review/edit → create. Falls back to manual
// CLAUDE.md textarea if synthesis fails (503 from disabled service or
// network blip) so the wizard isn't blocked on the LLM.
export const CreateProjectWizard: React.FC<Props> = ({ isOpen, serverId, onClose, onCreated }) => {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [skillLevel, setSkillLevel] = useState<ProjectSkillLevel>('auto');
  const [presetSlug, setPresetSlug] = useState('');
  const [freeform, setFreeform] = useState('');
  const [claudeMd, setClaudeMd] = useState('');
  const [presets, setPresets] = useState<ProjectPreset[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [synthesizing, setSynthesizing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [synthInfo, setSynthInfo] = useState<string | null>(null);

  useEffect(() => {
    if (!isOpen) return;
    listPresets().then(setPresets).catch((e) => {
      console.error('failed to load presets', e);
    });
  }, [isOpen]);

  // Reset on open
  useEffect(() => {
    if (isOpen) {
      setName('');
      setDescription('');
      setSkillLevel('auto');
      setPresetSlug('');
      setFreeform('');
      setClaudeMd('');
      setError(null);
      setSynthInfo(null);
    }
  }, [isOpen]);

  const synthesize = async () => {
    if (!name.trim()) {
      setError('Name is required before synthesizing.');
      return;
    }
    setSynthesizing(true);
    setError(null);
    setSynthInfo(null);
    try {
      const res = await synthesizeClaudeMD({
        server_id: serverId,
        preset_slug: presetSlug || undefined,
        name: name.trim(),
        description: description.trim(),
        skill_level: skillLevel,
        freeform: freeform.trim(),
      });
      setClaudeMd(res.claude_md);
      setSynthInfo(`Generated by ${res.provider}. Edit below before creating.`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Synthesis failed.';
      // 503 → tell the user they can still proceed manually.
      if (/unavailable|503/i.test(msg)) {
        setError('Synthesis is offline right now. You can write the CLAUDE.md manually below.');
      } else {
        setError(msg);
      }
    } finally {
      setSynthesizing(false);
    }
  };

  const submit = async () => {
    if (!name.trim()) {
      setError('Name is required.');
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      const project = await createProject({
        server_id: serverId,
        name: name.trim(),
        description: description.trim(),
        skill_level: skillLevel,
        preset_slug: presetSlug || undefined,
        claude_md: claudeMd,
      });
      onCreated(project);
      onClose();
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Failed to create project.';
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Create project">
      <div className="wizard-form">
        {error && <div className="wizard-error">{error}</div>}

        <label>
          Name
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            maxLength={80}
            placeholder="My new project"
            autoFocus
          />
        </label>

        <label>
          Description (optional)
          <input
            type="text"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="One-line summary"
          />
        </label>

        <label>
          Preset (optional)
          <select value={presetSlug} onChange={(e) => setPresetSlug(e.target.value)}>
            <option value="">No preset</option>
            {presets.map((p) => (
              <option key={p.slug} value={p.slug}>{p.name}</option>
            ))}
          </select>
        </label>

        <label>
          Skill level
          <select value={skillLevel} onChange={(e) => setSkillLevel(e.target.value as ProjectSkillLevel)}>
            {SKILL_LEVELS.map((s) => (
              <option key={s.value} value={s.value}>{s.label}</option>
            ))}
          </select>
        </label>

        <label>
          Describe what you want to build
          <textarea
            value={freeform}
            onChange={(e) => setFreeform(e.target.value)}
            placeholder={'A short paragraph or two: what is this project, who is it for, what does success look like? The more specific, the better the synthesized CLAUDE.md.'}
            style={{ minHeight: 110 }}
          />
        </label>

        <button
          type="button"
          className="projects-create-btn"
          onClick={synthesize}
          disabled={synthesizing || submitting || !name.trim()}
          style={{ alignSelf: 'flex-start' }}
        >
          <Sparkles size={14} />
          {synthesizing ? 'Synthesizing…' : claudeMd ? 'Re-synthesize' : 'Synthesize CLAUDE.md'}
        </button>

        {synthInfo && <div style={{ fontSize: 12, color: 'var(--parley-text-muted, #b9bbbe)' }}>{synthInfo}</div>}

        <label>
          CLAUDE.md (review and edit before creating)
          <textarea
            value={claudeMd}
            onChange={(e) => setClaudeMd(e.target.value)}
            placeholder={'# Project notes\n\nClick Synthesize above, or write this manually.'}
            style={{ minHeight: 220 }}
          />
        </label>

        <div className="wizard-actions">
          <button className="secondary" onClick={onClose} disabled={submitting || synthesizing}>Cancel</button>
          <button className="primary" onClick={submit} disabled={submitting || synthesizing || !name.trim()}>
            {submitting ? 'Creating…' : 'Create project'}
          </button>
        </div>
      </div>
    </Modal>
  );
};
